export const products = [
  {
    id: 1,
    name: "Áo Thun Nam Basic",
    price: 150000,
    description: "Áo thun nam chất liệu cotton thoáng mát, kiểu dáng đơn giản.",
    image: "https://bizweb.dktcdn.net/100/074/324/products/1610053227-0000004.jpg?v=1622553595563",
    category: "T-shirt",
  },
  {
    id: 2,
    name: "Áo Khoác Gió Nam",
    price: 350000,
    description: "Áo khoác chống nước, nhẹ nhàng, phù hợp khi đi phượt.",
    image: "https://1557691689.e.cdneverest.net/fast/1325x0/filters:format(webp)/static.5sfashion.vn/storage/product_color/izNSD1tG1VzaMCQaJstl5dRWbt2aoMlq.webp",
    category: "Jacket",
  },
  {
    id: 3,
    name: "Quần Jeans Slim Fit",
    price: 400000,
    description: "Quần jeans dáng ôm, co giãn tốt, phù hợp mọi phong cách.",
    image: "https://4menshop.com/images/thumbs/2019/08/quan-jean-slimfit-xanh-bien-qj1653-14633-slide-products-5d64ff79d9e5f.JPG",
    category: "Jeans",
  },
  {
    id: 4,
    name: "Áo Sơ Mi Trắng",
    price: 250000,
    description: "Áo sơ mi trắng cổ điển, thích hợp đi làm hoặc sự kiện.",
    image: "https://product.hstatic.net/200000588671/product/ao-so-mi-nam-bycotton-trang-art-nhan_8ec622a241ea4deb93a02bdbdcb87954.jpg",
    category: "Shirt",
  },
  {
    id: 5,
    name: "Quần Short Thể Thao",
    price: 200000,
    description: "Quần short thoáng mát, co giãn tốt cho hoạt động thể thao.",
    image: "https://bizweb.dktcdn.net/thumb/1024x1024/100/340/361/products/ib8162-21-model.jpg?v=1722053443267",
    category: "Shorts",
  },
  {
    id: 6,
    name: "Áo Hoodie Unisex",
    price: 450000,
    description: "Áo hoodie vải nỉ, form rộng, phù hợp cả nam và nữ.",
    image: "https://product.hstatic.net/200000886795/product/ao-hoodie-unisex-nam-nu-insidemen-ihd002bz__7__ff4a3abea33141b99dd7dd0ad98039ec.jpg",
    category: "Hoodie",
  },
  {
    id: 7,
    name: "Váy Maxi Nữ",
    price: 500000,
    description: "Váy maxi dài, chất liệu nhẹ nhàng, thích hợp đi biển.",
    image: "https://megafashion.vn/data/product/inn1716205275.jpg",
    category: "Dress",
  },
  {
    id: 8,
    name: "Bộ Đồ Ngủ Cotton",
    price: 300000,
    description: "Bộ đồ ngủ cotton mềm mại, thoải mái khi mặc ở nhà.",
    image: "https://aurakorea.com.vn/wp-content/uploads/2024/11/bo-do-ngu-mua-dong-2-1.jpg",
    category: "Sleepwear",
  },
  {
    id: 9,
    name: "Áo Dài Truyền Thống",
    price: 800000,
    description: "Áo dài Việt Nam truyền thống, phù hợp các dịp lễ.",
    image: "https://product.hstatic.net/200000037048/product/adtt_nha_an_mint_bc8788e0e4204599bd784c1759efc79e_master.jpg",
    category: "Traditional",
  },
  {
    id: 10,
    name: "Quần Tây Công Sở",
    price: 350000,
    description: "Quần tây dáng đứng, phù hợp phong cách công sở.",
    image: "https://bizweb.dktcdn.net/100/409/545/products/8f02cebe603fac61f52e12.jpg?v=1659689593013",
    category: "Formal",
  },
  {
    id: 11,
    name: "Áo Len Dệt Kim",
    price: 550000,
    description: "Áo len dệt kim cao cấp, giữ ấm hiệu quả cho mùa đông.",
    image: "https://i.imgur.com/XF2q2ji.jpg",
    category: "Sweater",
  },
  {
    id: 12,
    name: "Váy Dạ Hội Sang Trọng",
    price: 1200000,
    description: "Váy dạ hội lộng lẫy, phù hợp các buổi tiệc trang trọng.",
    image: "https://i.imgur.com/LmzGq4y.jpg",
    category: "Evening Dress",
  },
  {
    id: 13,
    name: "Áo Khoác Da Cao Cấp",
    price: 2000000,
    description: "Áo khoác da thật, thiết kế phong cách và bền bỉ.",
    image: "https://i.imgur.com/ncDkIKo.jpg",
    category: "Jacket",
  },
  {
    id: 14,
    name: "Áo Sơ Mi Kẻ Sọc",
    price: 350000,
    description: "Áo sơ mi kẻ sọc lịch lãm, phù hợp cả đi làm lẫn đi chơi.",
    image: "https://i.imgur.com/cWZ9aRA.jpg",
    category: "Shirt",
  },
  {
    id: 15,
    name: "Quần Legging Thể Thao",
    price: 250000,
    description: "Quần legging co giãn tốt, thoải mái cho các bài tập.",
    image: "https://i.imgur.com/5WqvKuW.jpg",
    category: "Sportswear",
  },
  {
    id: 16,
    name: "Áo Thun Polo Nam",
    price: 400000,
    description: "Áo thun polo nam thiết kế đơn giản, sang trọng.",
    image: "https://i.imgur.com/XWEuZnX.jpg",
    category: "T-shirt",
  },
  {
    id: 17,
    name: "Váy Ngắn Nữ Tính",
    price: 320000,
    description: "Váy ngắn nữ tính, chất liệu thoáng mát phù hợp mùa hè.",
    image: "https://i.imgur.com/dKa9DWg.jpg",
    category: "Skirt",
  },
  {
    id: 18,
    name: "Áo Hoodie Có Nón",
    price: 450000,
    description: "Áo hoodie thoải mái, dễ phối đồ cho phong cách năng động.",
    image: "https://i.imgur.com/RwLs6zG.jpg",
    category: "Hoodie",
  },
  {
    id: 19,
    name: "Quần Tây Nữ Công Sở",
    price: 500000,
    description: "Quần tây nữ lịch lãm, tạo điểm nhấn cho phong cách công sở.",
    image: "https://i.imgur.com/H2RGtfH.jpg",
    category: "Formal Pants",
  },
  {
    id: 20,
    name: "Áo Khoác Len Dày",
    price: 650000,
    description: "Áo khoác len dày dặn, giữ ấm tốt cho những ngày lạnh.",
    image: "https://i.imgur.com/N9Erv9e.jpg",
    category: "Cardigan",
  },
];
